### ISSUE TITLE
How to handle GHC beta versions?

### ISSUE THREAD

**Issue by sjakobi** [composewell/packcheck#15]
With

```
  - env: BUILD=cabal-new CABALVER=2.2 GHCVER=8.6.1
    addons: {apt: {packages: [cabal-install-2.2,ghc-8.6.1], sources: [hvr-ghc]}}
```

I [get](https://travis-ci.org/sjakobi/bsb-http-chunked/jobs/423341789#L634)

```
Found /opt/ghc/8.6.1/bin/ghc version [8.6.0.20180823] expecting [8.6.1]
Mismatching ghc version found at [/opt/ghc/8.6.1/bin], removing it from PATH and trying again
Found ghc version [8.6.0.20180823] expecting [8.6.1]
Error: Wrong ghc version [8.6.0.20180823] expected [8.6.1]
```

However if I would specify `GHCVER=8.6.0.20180823`, the build would break once hvr releases a new beta version.

Not sure if there's a good way to handle this.

**Comment by harendra-kumar** [comment]
What if you specify GHCVER=8.6? It would match 8.6.*, so that should work I guess.

**Comment by sjakobi** [comment]
It would be nice if `packcheck` could work like this, but it currently doesn't. It seems like `packcheck` constructs ghc's executable name from `GHCVER`:

```
Error: ghc 8.6 not found in PATH [/home/travis/.local/bin:/home/travis/.cabal/bin:/opt/cabal/2.2/bin:/opt/ghc/8.6/bin:/home/travis/.rvm/gems/ruby-2.4.1/bin:/home/travis/.rvm/gems/ruby-2.4.1@global/bin:/home/travis/.rvm/rubies/ruby-2.4.1/bin:/home/travis/.rvm/bin:/bin:/usr/bin]
```

**Comment by harendra-kumar** [comment]
It does work like that, I just tested it. It may be a problem specifically when using the `TOOLS_DIR` option perhaps. Can you try passing the path of the ghc 8.6 binary in `PATH=` environment variable?

**Comment by sjakobi** [comment]
Sorry, I probably wasn't quite clear: There is no `ghc-8.6` executable (link). There's `ghc-8.6.1` and there's something like `ghc-8.6.0.20180823`.

I suspect that `packcheck` can't find either of them given `GHCVER=8.6`.

**Comment by sjakobi** [comment]
Oops, sorry for mistrusting packcheck there! :)

After defining `PATH` as

```
  - PATH=/bin:/usr/bin:/opt/ghc/bin:/opt/ghc-ppa-tools/bin
```

it _did_ find the right compiler! Nice work! :)

I'm wondering though whether `packcheck` should add these directories to `PATH` by default?!

`haskell-ci` [also adds](https://github.com/haskell-CI/haskell-ci/blob/f67bc41621d40d6559684be5406d65409df4c480/.travis.yml#L63) `$HOME/local/bin` but I wasn't sure whether that would work with Travis' `env` configuration.

**Comment by harendra-kumar** [comment]
The problem may be that when finding ghc binary in the hvr ppa dir tree it matches only the exact compiler version while when finding in PATH it matches the prefix. I will try investigating and fixing it whenever I get some time. Until then you can leave this issue open.

**Comment by harendra-kumar** [comment]
Currently it uses the TOOLS_DIR env var to specify the hvr ppa and then searches for ghc in `${TOOLS_DIR}/ghc/${ver}*/`. Maybe I should drop using that mechanism and just ask the users to specify `/opt/ghc/bin` in PATH. Will that always work for hvr ppa? Or are there cases when we should use `${TOOLS_DIR}/ghc/${ver}*/` instead? I think I added mechanism this because of a problem you faced once in using the hvr ppa, not sure if that could have been resolved using the PATH instead.

I might consider adding this to default PATH, but generally I don't want to have such defaults as it may result in surprises, explicit specification by user always works best. We can add it as default in the CI config files though.

**Comment by sjakobi** [comment]
From my local Ubuntu machine:

```
$ ls /opt/ghc/bin/
cabal
ghc
ghc-7.0.4
ghc-7.10.3
ghc-7.2.2
ghc-7.4.2
ghc-7.6.3
ghc-7.8.4
ghc-8.0.2
ghc-8.2.2
ghc-8.4.1
ghc-8.4.2
ghc-8.4.3
ghc-8.6.0.20180823
ghc-8.6.1
ghc-8.7
ghc-8.7.20180827
ghc-head
ghci
ghci-7.0.4
ghci-7.10.3
ghci-7.2.2
ghci-7.4.2
ghci-7.6.3
ghci-7.8.4
ghci-8.0.2
ghci-8.2.2
ghci-8.4.1
ghci-8.4.2
ghci-8.4.3
ghci-8.6.0.20180823
ghci-8.6.1
ghci-8.7
ghci-8.7.20180827
ghci-head
ghc-pkg
ghc-pkg-7.0.4
ghc-pkg-7.10.3
ghc-pkg-7.2.2
ghc-pkg-7.4.2
ghc-pkg-7.6.3
ghc-pkg-7.8.4
ghc-pkg-8.0.2
ghc-pkg-8.2.2
ghc-pkg-8.4.1
ghc-pkg-8.4.2
ghc-pkg-8.4.3
ghc-pkg-8.6.0.20180823
ghc-pkg-8.6.1
ghc-pkg-8.7
ghc-pkg-8.7.20180827
ghc-pkg-head
haddock
haddock-ghc-7.0.4
haddock-ghc-7.10.3
haddock-ghc-7.2.2
haddock-ghc-7.4.2
haddock-ghc-7.6.3
haddock-ghc-7.8.4
haddock-ghc-8.0.2
haddock-ghc-8.2.2
haddock-ghc-8.4.1
haddock-ghc-8.4.2
haddock-ghc-8.4.3
haddock-ghc-8.6.0.20180823
haddock-ghc-8.6.1
haddock-ghc-8.7
haddock-ghc-8.7.20180827
haddock-ghc-head
runghc
runghc-7.0.4
runghc-7.10.3
runghc-7.2.2
runghc-7.4.2
runghc-7.6.3
runghc-7.8.4
runghc-8.0.2
runghc-8.2.2
runghc-8.4.1
runghc-8.4.2
runghc-8.4.3
runghc-8.6.0.20180823
runghc-8.6.1
runghc-8.7
runghc-8.7.20180827
runghc-head
```
```
$ ls /opt/ghc/8.6.1/bin/
ghc
ghc-8.6.0.20180823
ghci
ghci-8.6.0.20180823
ghc-pkg
ghc-pkg-8.6.0.20180823
haddock
haddock-ghc-8.6.0.20180823
hp2ps
hpc
hsc2hs
runghc
runghc-8.6.0.20180823
runhaskell
```

**Comment by harendra-kumar** [comment]
@sjakobi I updated the readme about picking GHC versions, take a look at #17 and let me know if anything needs correction.

**Comment by sjakobi** [comment]
@harendra-kumar #17 looks good to me! I don't currently use `packcheck` though so I probably wouldn't spot any problems.
