### ISSUE TITLE
Support cloning a repo before building

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/packcheck#30]
Packcheck was initially designed as a script to run on the existing CI systems which clone the repo and then run a script. To be able to run on any system, we can add support for a `PACKAGE_SOURCE_REPO` parameter to specify where to clone the repo from before a build. `packcheck` would then clone it first and then run inside the cloned repo as usual.

**Comment by harendra-kumar** [comment]
We can also support merging a PR before the build, by specifying the base branch and the PR branch. This will allow us to run CIs on any system without depending on any existing CI systems.

**Comment by adithyaov** [comment]
This is the functionality `packcheck-remote`.
Closed by #36
