### ISSUE TITLE
packcheck-remote CLI

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/packcheck#62]
1. [x] Should print help when no arguments are specified
2. [x] In the help it is not clear what force mode means
3. [x] In the help, not clear which arguments are optional which are mandatory, which take arguments etc
4. [ ] The way of passing arguments is not the same as standard unix CLI, it uses option=value format only.

**Comment by adithyaov** [comment]
See #61

**Comment by adithyaov** [comment]
Moved to #66
